#ifndef my_KEYBOARD
#define my_KEYBOARD
#include "TEXTUTIL.H"
char* GetKeyName(unsigned char key)
{
	switch(key)
	{
		case 0x00:return Text_Text("UnAssigned");
		case 0x01:return Text_Text("Escape");
		case 0x02:return Text_Text("&");
		case 0x03:return Text_Text("é");
		case 0x04:return Text_Text("\"UnAssigned");
		case 0x05:return Text_Text("'");
		case 0x06:return Text_Text("(");
		case 0x07:return Text_Text("-");
		case 0x08:return Text_Text("è");
		case 0x09:return Text_Text("_");
		case 0x0A:return Text_Text("ç");
		case 0x0B:return Text_Text("à");
		case 0x0C:return Text_Text(")");
		case 0x0D:return Text_Text("=");
		case 0x0E:return Text_Text("Backspc");
		case 0x0F:return Text_Text("Tab");

		case 0x10:return Text_Text("A");
		case 0x11:return Text_Text("Z");
		case 0x12:return Text_Text("E");
		case 0x13:return Text_Text("R");
		case 0x14:return Text_Text("T");
		case 0x15:return Text_Text("Y");
		case 0x16:return Text_Text("U");
		case 0x17:return Text_Text("I");
		case 0x18:return Text_Text("O");
		case 0x19:return Text_Text("P");
		case 0x1A:return Text_Text("^");
		case 0x1B:return Text_Text("$");
		case 0x1C:return Text_Text("Enter");
		case 0x1D:return Text_Text("Ctrl Left");
		case 0x1E:return Text_Text("Q");
		case 0x1F:return Text_Text("S");

		case 0x20:return Text_Text("D");
		case 0x21:return Text_Text("F");
		case 0x22:return Text_Text("G");
		case 0x23:return Text_Text("H");
		case 0x24:return Text_Text("J");
		case 0x25:return Text_Text("K");
		case 0x26:return Text_Text("L");
		case 0x27:return Text_Text("M");
		case 0x28:return Text_Text("%");
		case 0x29:return Text_Text("²");
		case 0x2A:return Text_Text("Left Shift");
		case 0x2B:return Text_Text("µ");
		case 0x2C:return Text_Text("W");
		case 0x2D:return Text_Text("X");
		case 0x2E:return Text_Text("C");
		case 0x2F:return Text_Text("V");

		case 0x30:return Text_Text("B");
		case 0x31:return Text_Text("N");
		case 0x32:return Text_Text(",");
		case 0x33:return Text_Text(";");
		case 0x34:return Text_Text(":");
		case 0x35:return Text_Text("!");
		case 0x36:return Text_Text("UnAssigned");
		case 0x37:return Text_Text("Pad *");
		case 0x38:return Text_Text("Alt");
		case 0x39:return Text_Text("Space");
		case 0x3A:return Text_Text("Caps Lock");
		case 0x3B:return Text_Text("F1");
		case 0x3C:return Text_Text("F2");
		case 0x3D:return Text_Text("F3");
		case 0x3E:return Text_Text("F4");
		case 0x3F:return Text_Text("F5");

		case 0x40:return Text_Text("F6");
		case 0x41:return Text_Text("F7");
		case 0x42:return Text_Text("F8");
		case 0x43:return Text_Text("F9");
		case 0x44:return Text_Text("F10");
		case 0x45:return Text_Text("Num. Lock");
		case 0x46:return Text_Text("Arret Defil.");
		case 0x47:return Text_Text("Pad 7");
		case 0x48:return Text_Text("Pad 8");
		case 0x49:return Text_Text("Pad 9");
		case 0x4A:return Text_Text("Pad -");
		case 0x4B:return Text_Text("Pad 4");
		case 0x4C:return Text_Text("Pad 5");
		case 0x4D:return Text_Text("Pad 6");
		case 0x4E:return Text_Text("Pad +");
		case 0x4F:return Text_Text("Pad 1");

		case 0x50:return Text_Text("Pad 2");
		case 0x51:return Text_Text("Pad 3");
		case 0x52:return Text_Text("Pad 0");
		case 0x53:return Text_Text("Pad del");
		case 0x54:return Text_Text("UnAssigned");
		case 0x55:return Text_Text("UnAssigned");
		case 0x56:return Text_Text("<");
		case 0x57:return Text_Text("F11");
		case 0x58:return Text_Text("F12");
		case 0x59:return Text_Text("UnAssigned");
		case 0x5A:return Text_Text("UnAssigned");
		case 0x5B:return Text_Text("UnAssigned");
		case 0x5C:return Text_Text("UnAssigned");
		case 0x5D:return Text_Text("UnAssigned");
		case 0x5E:return Text_Text("UnAssigned");
		case 0x5F:return Text_Text("UnAssigned");

		case 0x60:return Text_Text("UnAssigned");
		case 0x61:return Text_Text("UnAssigned");
		case 0x62:return Text_Text("UnAssigned");
		case 0x63:return Text_Text("UnAssigned");
		case 0x64:return Text_Text("UnAssigned");
		case 0x65:return Text_Text("UnAssigned");
		case 0x66:return Text_Text("UnAssigned");
		case 0x67:return Text_Text("UnAssigned");
		case 0x68:return Text_Text("UnAssigned");
		case 0x69:return Text_Text("UnAssigned");
		case 0x6A:return Text_Text("UnAssigned");
		case 0x6B:return Text_Text("UnAssigned");
		case 0x6C:return Text_Text("UnAssigned");
		case 0x6D:return Text_Text("UnAssigned");
		case 0x6E:return Text_Text("UnAssigned");
		case 0x6F:return Text_Text("UnAssigned");

		case 0x70:return Text_Text("UnAssigned");
		case 0x71:return Text_Text("UnAssigned");
		case 0x72:return Text_Text("UnAssigned");
		case 0x73:return Text_Text("UnAssigned");
		case 0x74:return Text_Text("UnAssigned");
		case 0x75:return Text_Text("UnAssigned");
		case 0x76:return Text_Text("UnAssigned");
		case 0x77:return Text_Text("UnAssigned");
		case 0x78:return Text_Text("UnAssigned");
		case 0x79:return Text_Text("UnAssigned");
		case 0x7A:return Text_Text("UnAssigned");
		case 0x7B:return Text_Text("UnAssigned");
		case 0x7C:return Text_Text("UnAssigned");
		case 0x7D:return Text_Text("UnAssigned");
		case 0x7E:return Text_Text("UnAssigned");
		case 0x7F:return Text_Text("UnAssigned");

		case 0x80:return Text_Text("UnAssigned");
		case 0x81:return Text_Text("UnAssigned");
		case 0x82:return Text_Text("UnAssigned");
		case 0x83:return Text_Text("UnAssigned");
		case 0x84:return Text_Text("UnAssigned");
		case 0x85:return Text_Text("UnAssigned");
		case 0x86:return Text_Text("UnAssigned");
		case 0x87:return Text_Text("UnAssigned");
		case 0x88:return Text_Text("UnAssigned");
		case 0x89:return Text_Text("UnAssigned");
		case 0x8A:return Text_Text("UnAssigned");
		case 0x8B:return Text_Text("UnAssigned");
		case 0x8C:return Text_Text("UnAssigned");
		case 0x8D:return Text_Text("UnAssigned");
		case 0x8E:return Text_Text("UnAssigned");
		case 0x8F:return Text_Text("UnAssigned");

		case 0x90:return Text_Text("UnAssigned");
		case 0x91:return Text_Text("UnAssigned");
		case 0x92:return Text_Text("UnAssigned");
		case 0x93:return Text_Text("UnAssigned");
		case 0x94:return Text_Text("UnAssigned");
		case 0x95:return Text_Text("UnAssigned");
		case 0x96:return Text_Text("UnAssigned");
		case 0x97:return Text_Text("UnAssigned");
		case 0x98:return Text_Text("UnAssigned");
		case 0x99:return Text_Text("UnAssigned");
		case 0x9A:return Text_Text("UnAssigned");
		case 0x9B:return Text_Text("UnAssigned");
		case 0x9C:return Text_Text("UnAssigned");
		case 0x9D:return Text_Text("Ctrl Right");
		case 0x9E:return Text_Text("UnAssigned");
		case 0x9F:return Text_Text("UnAssigned");

		case 0xA0:return Text_Text("UnAssigned");
		case 0xA1:return Text_Text("UnAssigned");
		case 0xA2:return Text_Text("UnAssigned");
		case 0xA3:return Text_Text("UnAssigned");
		case 0xA4:return Text_Text("UnAssigned");
		case 0xA5:return Text_Text("UnAssigned");
		case 0xA6:return Text_Text("UnAssigned");
		case 0xA7:return Text_Text("UnAssigned");
		case 0xA8:return Text_Text("UnAssigned");
		case 0xA9:return Text_Text("UnAssigned");
		case 0xAA:return Text_Text("UnAssigned");
		case 0xAB:return Text_Text("UnAssigned");
		case 0xAC:return Text_Text("UnAssigned");
		case 0xAD:return Text_Text("UnAssigned");
		case 0xAE:return Text_Text("UnAssigned");
		case 0xAF:return Text_Text("UnAssigned");

		case 0xB0:return Text_Text("UnAssigned");
		case 0xB1:return Text_Text("UnAssigned");
		case 0xB2:return Text_Text("UnAssigned");
		case 0xB3:return Text_Text("UnAssigned");
		case 0xB4:return Text_Text("UnAssigned");
		case 0xB5:return Text_Text("Pad /");
		case 0xB6:return Text_Text("UnAssigned");
		case 0xB7:return Text_Text("Imp. Ecran");
		case 0xB8:return Text_Text("Alt Gr");
		case 0xB9:return Text_Text("UnAssigned");
		case 0xBA:return Text_Text("UnAssigned");
		case 0xBB:return Text_Text("UnAssigned");
		case 0xBC:return Text_Text("UnAssigned");
		case 0xBD:return Text_Text("UnAssigned");
		case 0xBE:return Text_Text("UnAssigned");
		case 0xBF:return Text_Text("UnAssigned");

		case 0xC0:return Text_Text("UnAssigned");
		case 0xC1:return Text_Text("UnAssigned");
		case 0xC2:return Text_Text("UnAssigned");
		case 0xC3:return Text_Text("UnAssigned");
		case 0xC4:return Text_Text("UnAssigned");
		case 0xC5:return Text_Text("UnAssigned");
		case 0xC6:return Text_Text("UnAssigned");
		case 0xC7:return Text_Text("Home");
		case 0xC8:return Text_Text("UP");
		case 0xC9:return Text_Text("Page Up");
		case 0xCA:return Text_Text("UnAssigned");
		case 0xCB:return Text_Text("LEFT");
		case 0xCC:return Text_Text("UnAssigned");
		case 0xCD:return Text_Text("RIGHT");
		case 0xCE:return Text_Text("UnAssigned");
		case 0xCF:return Text_Text("End");

		case 0xD0:return Text_Text("DOWN");
		case 0xD1:return Text_Text("Page Down");
		case 0xD2:return Text_Text("Insert");
		case 0xD3:return Text_Text("Delete");
		case 0xD4:return Text_Text("UnAssigned");
		case 0xD5:return Text_Text("UnAssigned");
		case 0xD6:return Text_Text("UnAssigned");
		case 0xD7:return Text_Text("UnAssigned");
		case 0xD8:return Text_Text("UnAssigned");
		case 0xD9:return Text_Text("UnAssigned");
		case 0xDA:return Text_Text("UnAssigned");
		case 0xDB:return Text_Text("Win Left");
		case 0xDC:return Text_Text("Win Right");
		case 0xDD:return Text_Text("Prop.");
		case 0xDE:return Text_Text("UnAssigned");
		case 0xDF:return Text_Text("UnAssigned");

		case 0xE0:return Text_Text("UnAssigned");
		case 0xE1:return Text_Text("UnAssigned");
		case 0xE2:return Text_Text("UnAssigned");
		case 0xE3:return Text_Text("UnAssigned");
		case 0xE4:return Text_Text("UnAssigned");
		case 0xE5:return Text_Text("UnAssigned");
		case 0xE6:return Text_Text("UnAssigned");
		case 0xE7:return Text_Text("UnAssigned");
		case 0xE8:return Text_Text("UnAssigned");
		case 0xE9:return Text_Text("UnAssigned");
		case 0xEA:return Text_Text("UnAssigned");
		case 0xEB:return Text_Text("UnAssigned");
		case 0xEC:return Text_Text("UnAssigned");
		case 0xED:return Text_Text("UnAssigned");
		case 0xEE:return Text_Text("UnAssigned");
		case 0xEF:return Text_Text("UnAssigned");

		case 0xF0:return Text_Text("UnAssigned");
		case 0xF1:return Text_Text("UnAssigned");
		case 0xF2:return Text_Text("UnAssigned");
		case 0xF3:return Text_Text("UnAssigned");
		case 0xF4:return Text_Text("UnAssigned");
		case 0xF5:return Text_Text("UnAssigned");
		case 0xF6:return Text_Text("UnAssigned");
		case 0xF7:return Text_Text("UnAssigned");
		case 0xF8:return Text_Text("UnAssigned");
		case 0xF9:return Text_Text("UnAssigned");
		case 0xFA:return Text_Text("UnAssigned");
		case 0xFB:return Text_Text("UnAssigned");
		case 0xFC:return Text_Text("UnAssigned");
		case 0xFD:return Text_Text("UnAssigned");
		case 0xFE:return Text_Text("UnAssigned");
		case 0xFF:return Text_Text("UnAssigned");
	}

	return NULL;
}
#endif